### ISSUE TITLE
Remove new lines from SelectorHTML values

### ISSUE THREAD

**Issue by dasaveliev** [martinsbalodis/web-scraper-chrome-extension#121]
Because of a crappy HTML layout, if there's a linefeed (LF) in the SelectorHTML field value, when exporting to .csv, those LF brake the fields structure.

**Comment by dasaveliev** [comment]
For example, we have a data structure columns like name, surname, description.
The description field is of type SelectorHTML and the source html code like this (description3 further):
<div><p>Title</p> LF <span>Description text<span></div>
where LF stands for Line Feed of new Line, that is:

<div><p>Title</p>
<span>Description text<span></div>

then, when exporting to .csv, we have kinda this:
"John","Doe","<p>Some description text</p>"
"Bob","Brown","<div>Some info abt Bobby</div>"
"Yan","Glazoff","<h1>About Yan</h1>
<div>Some info abt Yan</div>"

Easy to see, that instead of having three data rows we get four rows and the data fields structure is broken.

To workaroud this for now, you may use Notepad++, then Find (Ctrl+F), check the Regular expression radio button in the bottom, check the Wrap around check box, choose Replace tab, fill in the fields:
Regular expression: ([^"])\n
Replace: $1

This will remove all the extra new lines, that meet the condition: the new line is not after the " (quote symbol).

However, before ronning replace all over the data, please check that it finds the correct new lines by running Find (not Replace) first with the Show All Characters button pressed at the top buttons menu in the Notepad++ window (not in the Find dialog).

**Comment by martinsbalodis** [comment]
The CSV file isn't broken by this. Software that is reading the file as CSV not as plain text will understand that there are simply newlines in cells. 

https://en.wikipedia.org/wiki/Comma-separated_values#General_functionality
