### ISSUE TITLE
selecting text

### ISSUE THREAD

**Issue by lctreb** [martinsbalodis/web-scraper-chrome-extension#125]
Hi
I can't understand why I can't select text in a certain zone of the web page.
Selector : "contacts" doesn't give any data

Site map :
{"startUrl":"http://www.cnc.fr/web/fr/aides-et-commissions","selectors":[{"parentSelectors":["_root"],"type":"SelectorLink","multiple":true,"id":"categorie","selector":"ul.layouts a","delay":"500"},{"parentSelectors":["categorie"],"type":"SelectorLink","multiple":true,"id":"etape","selector":"ul.ui-tabs-nav.maintabs a","delay":"500"},{"parentSelectors":["etape"],"type":"SelectorLink","multiple":true,"id":"aide","selector":"a.titre","delay":"500"},{"parentSelectors":["aide"],"type":"SelectorText","multiple":true,"id":"demandeur","selector":"div.section:nth-of-type(3) span.fontcolor-100","regex":"","delay":""},{"parentSelectors":["aide"],"type":"SelectorText","multiple":false,"id":"intitule","selector":"a.breadcrumb-link:nth-of-type(3)","regex":"","delay":""},{"parentSelectors":["aide"],"type":"SelectorText","multiple":false,"id":"contacts","selector":"div#article_18_7547567_1.3.journal-content-article ul.bgcolor-20","regex":"","delay":""}],"_id":"cnc"}

URL : http://www.cnc.fr/web/fr/aides-et-commissions

Don't know if if it's a bug.
If not, i'd be happy to solve my problem.

Cheers

**Comment by sntran** [comment]
For "contacts", the selector is using ID of the article, which is very specific to a single page only.

Try to change the selector to `.contact-colonne` instead of `div#article_18_7547567_1.3.journal-content-article ul.bgcolor-20`.

**Comment by lctreb** [comment]
It works fine
Many thanks
