### ISSUE TITLE
Can this extension flag/mark/open pages that contain certain words?

### ISSUE THREAD

**Issue by Jyqft** [martinsbalodis/web-scraper-chrome-extension#133]
For example, the extension will only copy to the CSV if the element text value contains a certain keyword, or it'll only open links that contain certain keywords.

**Comment by martinsbalodis** [comment]
You can use a custom css selector. For example - `a:contains('custom text')`

**Comment by Jyqft** [comment]
That css selector only reads the custom text of the link itself, right? For example, if you require a keyword of 'Google' and you have a link like [This link takes you to Google](http://www.google.com), that link, and only that link will be selected?

**Comment by martinsbalodis** [comment]
It will select any link that contains 'Google'

**Comment by Jyqft** [comment]
I see. So basically, this still hinges on knowing the HTML structure, right? Can you do something like `*:contains('custom text')` (or if my CSS selection is wrong, I meant the asterisk to represent all elements)?

**Comment by martinsbalodis** [comment]
Yes you can use the `*` like that.
