### ISSUE TITLE
[Question] How does one use the Regex text field with Text type selectors?

### ISSUE THREAD

**Issue by Jyqft** [martinsbalodis/web-scraper-chrome-extension#134]
I've looked through the three tutorial videos, as well as the WebScraper.io documentation, and I haven't come across any explanation for its usage.

**Comment by martinsbalodis** [comment]
Here is an example how it would work:
 * html element: `<span>id - 12345</span>`
 * CSS selector: `span`
 * regex: `[0-9]+`
 * result: `12345`
 * result without regex: `id - 12345`
