### ISSUE TITLE
Scrapped columns are not correctly associated

### ISSUE THREAD

**Issue by michelMuv** [martinsbalodis/web-scraper-chrome-extension#150]
I am trying to export establishment names and addresses from a web page but the address columns doesn't much their establishments.  Sometime I can find the correct address 5 or 30 lines bellow the establishments

The site map and csv snaphsot are attached. 

[sitemap.txt](https://github.com/martinsbalodis/web-scraper-chrome-extension/files/221361/sitemap.txt)
![scrap](https://cloud.githubusercontent.com/assets/1659689/14568253/18ed3722-0306-11e6-97b7-8e8ee8ffba18.png)

Chrome version 50.0.2661.75 (64-bit), 
OS Ubuntu 14.04 LTS
Website link => https://www.zomato.com/montreal/restaurants

**Comment by dtriantafyllides** [comment]
I'm having the exact same problem.  Have you had any luck in solving?

**Comment by martinsbalodis** [comment]
You need to use element selector to separate records within one page. There are a lot of posts about this in forum.
