### ISSUE TITLE
element selector not visible 

### ISSUE THREAD

**Issue by soedr** [martinsbalodis/web-scraper-chrome-extension#152]
The field that appears in the video tutorials (see screen shot) does not apppear when I click "select"
<img width="640" alt="screen shot 2016-04-24 at 8 48 27 pm" src="https://cloud.githubusercontent.com/assets/16186699/14768907/17a44e50-0a5e-11e6-94f4-5bb4616dc231.png">

**Comment by martinsbalodis** [comment]
Can you post a link to this site where the element selection doesn't work?

**Comment by ruurtjan** [comment]
http://webscraper.io/test-sites/e-commerce/allinone
Doesn't work for me on Chrome (Version 50.0.2661.86 (64-bit) on Ubuntu) with WebScraper 0.2.0.10.

**Comment by drjaydenm** [comment]
^ Also doesn't work for me on the test website above. It seems none of the buttons on the add selector page work. Even if typing a selector manually, all fields show green but the Save Selector button doesn't work. Chrome 50.0.2661.102 on Windows x64 WebScraper 0.2.0.10

**Comment by vineetshetty** [comment]
+1

**Comment by joshkpeterson** [comment]
Folks it only works when you put dev inspector docked to the bottom of the page! 🙌

Hat tip to this thread on reddit: https://www.reddit.com/r/datasets/comments/1reixf/web_scraper_chrome_extension/

@martinsbalodis Maybe this will help you fix this or at least add a really obvious note in the documentation.

**Comment by PreethikaShankar** [comment]
for me also selectors not working. i have developer tool in the bottom only and i tried in multiple sites. please help.
