### ISSUE TITLE
pagination done using javascript

### ISSUE THREAD

**Issue by eijoac** [martinsbalodis/web-scraper-chrome-extension#153]
I have a case that the next page link is done using javascript.

`<a href="#" onclick="Search.page(5)">Next</span></a>`

"Search.page(i)", where "i" is the next page, i.e. if on page 4, i = 5 (the above case), and so on. Is there a way to scrape such site? Thanks.

update: the actual page urls are straight forwards once clicking the link, ex,

abc.com/xyz&page=4
abc.com/xyz&page=5

**Comment by riderx** [comment]
you can use range value in sitemap data using abc.com/xyz&page=[1-25] for exemple
