### ISSUE TITLE
Having trouble scrapping ad images from a customer to customer based website

### ISSUE THREAD

**Issue by Saif03** [martinsbalodis/web-scraper-chrome-extension#156]
when I try to scrap images using below setup it doesn't gives any thing in the images column. Also I wanted to scrap phone number available at the right but I wasn't able to as it didn't provided any option to be selecting phone number. So I had to select the parent element of the phone number.

{"startUrl":"https://www.olx.com.pk/other-pets/q-cat/?page=1","selectors":[{"parentSelectors":["_root"],"type":"SelectorLink","multiple":true,"id":"adv","selector":"tr:nth-of-type(n+4) a.marginright5","delay":""},{"parentSelectors":["adv"],"type":"SelectorText","multiple":false,"id":"name","selector":"h1.brkword","regex":"","delay":""},{"parentSelectors":["adv"],"type":"SelectorText","multiple":false,"id":"owner","selector":"span.block.brkword","regex":"","delay":""},{"parentSelectors":["adv"],"type":"SelectorText","multiple":false,"id":"price","selector":"strong.xxxx-large","regex":"","delay":""},{"parentSelectors":["adv"],"type":"SelectorText","multiple":false,"id":"city","selector":"strong.c2b","regex":"","delay":""},{"parentSelectors":["adv"],"type":"SelectorText","multiple":false,"id":"time","selector":"span.pdingleft10","regex":"","delay":""},{"parentSelectors":["adv"],"type":"SelectorText","multiple":false,"id":"desc","selector":"p.pding10","regex":"","delay":""},{"parentSelectors":["adv"],"type":"SelectorText","multiple":false,"id":"phone","selector":"div.contactbox","regex":"","delay":""},{"parentSelectors":["adv"],"type":"SelectorLink","multiple":true,"id":"images","selector":"ul.overh li.fleft","delay":""}],"_id":"cats"}

**Comment by martinsbalodis** [comment]
Use image selector instead of link selector to select images.
