### ISSUE TITLE
Scrape Updates

### ISSUE THREAD

**Issue by robbiewalters** [martinsbalodis/web-scraper-chrome-extension#163]
Is there a way to only scrape for updates to a website? I'm trying to build a list of all the companies for sale in the U.S through bizbuysell.com. After I scrape the website once and get my list I would like to check every week for new additions. 

Is this possible or do I need to re-scrape the entire site every week and then compare the outputs to find the differences?

Thanks for the help.

**Comment by arunbanakar123** [comment]
Presently that feature is not available for this app, better Martin will
give you technical reason for this.

**Comment by martinsbalodis** [comment]
How could a crawler know that the page has changes without looking at it? I would say that you need to recrawl everything and then compare the results with a script.

**Comment by robbiewalters** [comment]
Makes sense, thanks
