### ISSUE TITLE
Element attribute web scraper

### ISSUE THREAD

**Issue by kshort31** [martinsbalodis/web-scraper-chrome-extension#164]
I'm having trouble separating "Asking Price" and the actual price using web scraper, as shown in the attached photo. Element attribute seems to be the only option for separating the two fields. What do I need to place in the "attribute name" field of the selector tool in web scraper to only extract the actual price and not the title beside the actual price? 

![image](https://cloud.githubusercontent.com/assets/21222888/17937255/6a49fe34-69ef-11e6-9b9e-01656146a546.png)

**Comment by martinsbalodis** [comment]
Hi,
You will need to write a custom CSS selector. it might look something like this -  `div:contains('Asking Price')+div`
