### ISSUE TITLE
problem w/ Query string pagination 

### ISSUE THREAD

**Issue by williamzmtan** [martinsbalodis/web-scraper-chrome-extension#170]
Set up the web scraper to scrape all "Septic Tanks & Systems Cleaning" on the Better Business Bureau website but had a problem selecting all the pages on the query string pagination. When selected, the scraper only scrapes the listed pages 1, 2, 3, 4, & 294, but doesn't scrape pages 5-293. 

Attached below is the page I used. 
http://www.bbb.org/search/?type=category&input=Septic+Tanks+%26+Systems+Cleaning&location=&filter=business&accredited=&radius=5000&country=USA%2c+CAN&language=en&codeType=YPPA&page=1&source=

**Comment by martinsbalodis** [comment]
You are probably using link selector. The link selector must be set as a parent to itself. Then it will find new pagination links while it is visiting pagination links.
