### ISSUE TITLE
Not all elements scraped, and many wrongly placed

### ISSUE THREAD

**Issue by Mohamed3on** [martinsbalodis/web-scraper-chrome-extension#172]
Hi,
When I try to scrape Buzzsumo.com, it creates an incomplete list, with many elements missing, and many in the wrong place. However, when trying to preview them, it works perfectly.
I tried increasing page load delay, but it did not help.

**Comment by martinsbalodis** [comment]
Probably you have multiple text selectors with multiple option checked. Web Scraper isn't combining data from multiple selectors with multiple option checked. You need to use element selector to select wrapper elements and then extract data within each wrapper element.
