### ISSUE TITLE
Project is dead?

### ISSUE THREAD

**Issue by webdevsega** [martinsbalodis/web-scraper-chrome-extension#173]
Author you will no longer support this project? I believe that such a great product does not have to die. Thank you.

**Comment by martinsbalodis** [comment]
It's not dead. I am working on it full time. Extension development is on pause at the moment. I am waiting for some es6 features.

**Comment by webdevsega** [comment]
@martinsbalodis Thanks for the info. When we can presumably get the features from PRs?
