### ISSUE TITLE
csv Format/layout

### ISSUE THREAD

**Issue by QwertyZW** [martinsbalodis/web-scraper-chrome-extension#180]
Sometimes I'd like a sibling of a parent link to be included in the same row as the children of that parent's link.

EG
```
link     ----> child1
memo           child2
```
I'd like the final output to have the columns
```
link, memo, child1, child2
```
Instead of 
```
link, child1, child2
```
and memo in a different row

**Comment by martinsbalodis** [comment]
You extract the memo data if it doesn't have multiple option checked.
