### ISSUE TITLE
tool bar is blank in Chrome Version 56.0.2924.87 (64-bit)

### ISSUE THREAD

**Issue by myahes** [martinsbalodis/web-scraper-chrome-extension#185]
I open up the webscraper tool and see the below.  any ideas?

![new issue martinsbalodis web-scraper-chrome-extension 2017-02-03 09-10-06](https://cloud.githubusercontent.com/assets/25534123/22600736/aaae4d00-e9f0-11e6-8ec1-754dcccb44b3.png)

**Comment by gaochangkuan** [comment]
I have the same problem~

**Comment by arunbanakar123** [comment]
Press Ctrl+Shift+i
Press "Customize and control DevTools" (right side of Dev. Panel - 3 dots)

Dock side - "Dock to Bottom"


When u change 'DevTool' settings to "Docked to Side" or "Undocked" it will
not works, don’t know exact reason.

**Comment by gaochangkuan** [comment]
Thanks for your enthusiastic answer!





------------------ 原始邮件 ------------------
发件人: "arunbanakar123";<notifications@github.com>;
发送时间: 2017年2月21日(星期二) 下午5:58
收件人: "martinsbalodis/web-scraper-chrome-extension"<web-scraper-chrome-extension@noreply.github.com>; 
抄送: "高长宽"<172012241@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [martinsbalodis/web-scraper-chrome-extension] tool bar is blankin Chrome Version 56.0.2924.87 (64-bit) (#185)



Press Ctrl+Shift+i
 Press "Customize and control DevTools" (right side of Dev. Panel - 3 dots)
 
 Dock side - "Dock to Bottom"
 
 
 When u change 'DevTool' settings to "Docked to Side" or "Undocked" it will
 not works, don’t know exact reason.
