### ISSUE TITLE
I cannot apply a selector for a tab on flaschscores.com.

### ISSUE THREAD

**Issue by kuisza** [martinsbalodis/web-scraper-chrome-extension#188]
I would like to create a selector inside this link. I would like to have the selector selecting the 'H2H' tab, as my attached photo shows. I don't know which select type should I apply here. Can you help me on that please?

https://lh3.googleusercontent.com/-RMXLXuFRpyQ/WJivtIjErJI/AAAAAAAAGlk/5uQz6flxRhUsaW8VQbidp6rGMpIVCjudwCLcB/s1600/h2h.png

**Comment by arunbanakar123** [comment]
Use 'Element click' selector, for H2H tab use this css '
*#a-match-head-2-head*' (without single quotes).

**Comment by kuisza** [comment]
thank you arunbanakar123, it work smoothly :) 

how do you get css like *#a-match-head-2-head*' ?  and to select the 'Show more matches', should I also use Element click?
