### ISSUE TITLE
I cannot apply another selector on flaschscores.com.

### ISSUE THREAD

**Issue by kuisza** [martinsbalodis/web-scraper-chrome-extension#189]
I would like to create a selector inside this link. I would like to have the selector selecting 'Show more matches' and let the page show the other games, as my attache photo demonstrates. (https://goo.gl/VjqhL5) I don't know which select type should I apply here. Can you help me on that please?

**Comment by martinsbalodis** [comment]
Element click selector with "Load More" option could solve this.
