### ISSUE TITLE
create new sitemap is disabled

### ISSUE THREAD

**Issue by kavyashivakumar** [martinsbalodis/web-scraper-chrome-extension#197]
Hi, 

can you please help?
i've installed the extension. but createnew sitemap is disabled. i can't seem to understand why

**Comment by arunbanakar123** [comment]
Can you please send screenshot....

**Comment by kavyashivakumar** [comment]
![image](https://cloud.githubusercontent.com/assets/17231761/24418719/cbf9c26e-13e4-11e7-93b7-b576451991dc.png)


here it is

**Comment by arunbanakar123** [comment]
Press Ctrl+Shift+i
Press "Customize and control DevTools" (right side of Dev. Panel - 3 dots)

Dock side - "Dock to Bottom"


When u change 'DevTool' settings to "Docked to Side" or "Undocked" it will
not works, don’t know exact reason.

**Comment by jwillmer** [comment]
solved?

**Comment by kavyashivakumar** [comment]
@jwillmer , thank you. yes its resolved. appreciate you following up
