### ISSUE TITLE
Web Data Blank

### ISSUE THREAD

**Issue by ura17** [martinsbalodis/web-scraper-chrome-extension#206]
Hi,

I want to scrap the data from this website http://v3au.zone-secure.net/drive/9006/287176/#page=1
but when i open the developer tool there's no data shown.

Screenshot below 
![image](https://cloud.githubusercontent.com/assets/28971531/26479138/46308c2c-41fb-11e7-9d53-1b94a86366dc.png)

Please help!

Thanks

**Comment by arunbanakar123** [comment]
@jwillmer, can you please implement it, when someone try to open Web
scraper in side dock, alert them to use in centre down dock.

**Comment by jwillmer** [comment]
Yes, this is really annoying! I will take care of it.

**Comment by jwillmer** [comment]
Done: https://github.com/jwillmer/web-scraper-chrome-extension/commit/bea5f2145142c869ee8f701e641a2c6b788deed9

Use the fork to get the feature: https://github.com/jwillmer/web-scraper-chrome-extension
