### ISSUE TITLE
More Tutorials

### ISSUE THREAD

**Issue by ubuntume** [martinsbalodis/web-scraper-chrome-extension#207]
Hello, I've been using the extension for a few weeks now. I am having an issue understanding how I would go about scraping something like this: 
![tre modal](https://cloud.githubusercontent.com/assets/17444017/26521933/e1cff09c-42c2-11e7-98db-2588d2ff1d1e.PNG)

source url: http://treperformance.com/i-23899588-corvette-z06-ls7-2006-2013-procharger-intercooled-race-kit-w-f-1d-f-1-or-f-1a.html

I haven't seen any documentation get more indepth.

I need all of the text titles and all of the text in the drop down and the prices...... How?

**Comment by jwillmer** [comment]
You might be able to manage to get it by using `Click Selector` > `Element Selector` > `etc` but the simplest thing is if you just use the `HTML selector` on the page to select the JavaScript part and use regex to grab the JSON part you are interested in this is how I would do it!

![json](https://cloud.githubusercontent.com/assets/1503577/26548116/289091bc-447b-11e7-989d-990dc7019737.png)
