### ISSUE TITLE
URI validation forbids running scraper on file://

### ISSUE THREAD

**Issue by jnothman** [martinsbalodis/web-scraper-chrome-extension#214]
The startURL validators in `Controller.js` include bootstrapValidator's `uri` validator. This validator only allows http(s) and ftp URIs. However, it may be good practice to scrape a web site one has downloaded onto a local machine. Disallowing a startURL with the file:// protocol makes this hard (without launching a static web server, at least!).

**Comment by martinsbalodis** [comment]
Chrome extensions cannot access local files. This limitation is probably made due to security reasons. Otherwise chrome extensions might gain access to sensitive information on users computer.

The workaround would be to run a web server locally.
