### ISSUE TITLE
Web Scraper stopped by .doc file

### ISSUE THREAD

**Issue by scooterbrown** [martinsbalodis/web-scraper-chrome-extension#217]
My company links selector stops my web scrape when it encounters a document link. It can click through the jpg and pdf files, but it tries to start a download of Doc files and stops the web scraper entirely.

Is there a way to avoid doc files or stop pagination at a specific page?

My sitemap is below:

{"startUrl":"http://www.mhi.org/members?page=1","selectors":[{"parentSelectors":["_root","Pagination"],"type":"SelectorLink","multiple":true,"id":"Company Links","selector":"h3 a","delay":""},{"parentSelectors":["Company Links"],"type":"SelectorText","multiple":false,"id":"Company Name","selector":"h2.contrast","regex":"","delay":""},{"parentSelectors":["Company Links"],"type":"SelectorText","multiple":false,"id":"Address","selector":"div.microsite-contact p","regex":"","delay":""},{"parentSelectors":["Company Links"],"type":"SelectorText","multiple":false,"id":"Contact Info","selector":"div#contact-name","regex":"","delay":""},{"parentSelectors":["Company Links"],"type":"SelectorLink","multiple":false,"id":"Website Link","selector":"div.microsite-contact a.btn","delay":""},{"parentSelectors":["Company Links"],"type":"SelectorText","multiple":false,"id":"Phone","selector":"div#contact-phone","regex":"","delay":""},{"parentSelectors":["Company Links"],"type":"SelectorText","multiple":false,"id":"Company Fax","selector":"div#contact-fax","regex":"","delay":""},{"parentSelectors":["Company Links"],"type":"SelectorText","multiple":false,"id":"Company Email Contact","selector":"div#contact-email a.accent","regex":"","delay":""},{"parentSelectors":["_root","Pagination"],"type":"SelectorLink","multiple":true,"id":"Pagination","selector":"li.pgNum:nth-of-type(n+3) a","delay":""}],"_id":"mhi"}

Thanks ahead of time for the help!

**Comment by alexandru-porcescu** [comment]
@jwillmer has done a great job collecting/merging various features in his fork [https://github.com/jwillmer/web-scraper-chrome-extension](web-scraper-extension) 
in his fork the ability to limit pagination is present

**Comment by jwillmer** [comment]
@alexandru-porcescu  Thx for the reference and the compliment but you managed to add a broken link, the fixed link would be: https://github.com/jwillmer/web-scraper-chrome-extension

**Comment by martinsbalodis** [comment]
You can try to modify the css selector to make it skip specific elements.
A link selector that ignores specific text
```
a:not(:contains('text to ignore'))
```
A link selector that ignores attribute contents:
```
a:not([href*='.doc'])
```
