### ISSUE TITLE
Get attributes of the selected Element itself

### ISSUE THREAD

**Issue by ehausen** [martinsbalodis/web-scraper-chrome-extension#222]
I have a long list of event on a website, like so:
```
<div class="event-list">
<div class="event" data-title="data123" data-more="xxx">
  <p>Text Content</p>
</div>
<div class="event" data-title="dataXYZ" data-more="xxx">
  <p>Text Content</p>
</div>
<div class="event" data-title="dataABC" data-more="xxx">
  <p>Text Content</p>
</div>
</div>
```
I want to extract the data-title, data-more and other attributes of the selected Element itself.

I'm able to select Text Content inside the Element I select. (Select .event, multiple --> Element), but how dow I get all those attributes of the Element in a nice table?

**Comment by martinsbalodis** [comment]
Use Element attribute selector to extract element attributes.
