### ISSUE TITLE
Webscraper stops due to insecure website

### ISSUE THREAD

**Issue by dnlmzw** [martinsbalodis/web-scraper-chrome-extension#227]
Hi there,

First of all, love the work you've done with Webscraper! Really helpful once you get the hang of it.

I've run into a bit of an issue that blocks the entire scraping chain, as my Chrome Browser on Mac (version 60.0.3112.113 (Officiel version) (64-bit)) stops due to encountering an insure website.

"The site, you're trying to access, contains malware".

I'm attaching a screenshot as a reference here:

![Safety error](https://i.imgur.com/7IF8uq7.png)

I've tried to ignore this message, by pressing the "Back to safety"-button, but unfortunately, this stops the scraping.

**Comment by martinsbalodis** [comment]
You can try to disable insecure certificate security measure. Go to chrome://flags/#allow-insecure-localhost and enable "Allow invalid certificates for resources loaded from localhost"

**Comment by martinsbalodis** [comment]
Some sites might have self generated SSL certificates. To scrape them you will need to launch chrome with additional parameter.

Windows:
Create chrome shortcut and add --ignore-certificate-errors parameter.

osx, Linux:
Launch chrome from terminal:

chrome --ignore-certificate-errors
