### ISSUE TITLE
URL range (Increment two integer)

### ISSUE THREAD

**Issue by norman10** [martinsbalodis/web-scraper-chrome-extension#229]
Hi Guys,

Do you have an idea how to scrape all items in this site?

[http://www.acmecontrols.com/Shop-All-Manufacturer_2/GC-Valves?range=51%2C100%2C1891](http://www.acmecontrols.com/Shop-All-Manufacturer_2/GC-Valves?range=51%2C100%2C1891)

It has two integer that increment in every page.

I tried to range the URL with this to increment integer in every page:

http://www.acmecontrols.com/Shop-All-Manufacturer_2/GC-Valves?range=[51-1891:50]%2C[100-1891:50]%2C1891

but it return an error:

![image](https://user-images.githubusercontent.com/29930081/30921751-39b262c8-a375-11e7-91e5-ca60d6c7e146.png)

Thanks,
Romz

**Comment by martinsbalodis** [comment]
Currently there isn't a way to use two number ranges in the url. The main problem is that in these cases not all number variations are needed. Probably an url with numbers 2000, 100 won't work in the site.

Right now the only way to solve this is to generate a list of urls yourself and import them into the sitemap. 
You can do this in multiple ways:

 * Copy each url into the sitemap
 * Add two urls to the sitemap. Then export it and add the rest of the urls in sitemap code. Then import the sitemap.
 * Host the url list in a website and using link selector navigate to those urls
