### ISSUE TITLE
Many observations report "null" and "0" when exporting as .CSV files

### ISSUE THREAD

**Issue by UYScutti** [martinsbalodis/web-scraper-chrome-extension#230]
I try to extract pages such as this: http://www.voobly.com/match/view/16434172 for P1 Gold, yet the .csv reports the data entry as "null" inconsistently.  This is a problem for a project I am doing.  Does anyone have any more information on this?

**Comment by waynieoaks** [comment]
Hi

I too am starting to see this in time fields where the scraper captures the time correctly but in the export to csv it is returning null. I have not changed the scraper - it has just suddenly started happening. 

Many thanks.

**Comment by martinsbalodis** [comment]
"null" in the export means that the element wasn't found in the page. "" or empty value means that the element was present but it didn't contain any text. 

Try checking how the selector works in different pages of the site. Use element preview/data preview.
