### ISSUE TITLE
Rows not matching

### ISSUE THREAD

**Issue by digosm** [martinsbalodis/web-scraper-chrome-extension#231]
![capturar](https://user-images.githubusercontent.com/32524259/31193667-2cb87aac-a91b-11e7-9090-a7e0979f2c49.PNG)

Does any body have any idea why is that happening?

The website is https://www.ifood.com.br/delivery/vitoria-es/china-in-box---vitoria-praia-do-sua

**Comment by Edge-Rider** [comment]
It happen because inside web page HTML tags there's tab o \n
Would be useful if webscraper clear text before importing

**Comment by jmk201** [comment]
Is there a solution to this issue? I am trying it on https://www.homeaway.com and downloaded rows dont match. Any thoughts or workaround?

**Comment by martinsbalodis** [comment]
This is a common mistake. Basically you have 2+ selectors alongside with multiple option checked. Web Scraper doesn't try to merge data from selectors with multiple option checked. Instead the data is stored into different rows.

The correct way too do this is to use element selector to select wrapper elements of the elements that contain data. Then add child selectors to the element selector with multiple option not checked. You can see an example here - http://webscraper.io/documentation#element-selector
