### ISSUE TITLE
Multiple URL Feature to Permit Copy and Paste from Large Spreadsheets?

### ISSUE THREAD

**Issue by UYScutti** [martinsbalodis/web-scraper-chrome-extension#233]
When you select a sitemap, and go to Edit Metadata, can a feature be added to copy and paste a lot of URLs from a single spreadsheet column into the metadata URLs in Webscraper.io?  I know you can press the + button to add another entry, but I'm thinking that this would make it easier for a lot of users like myself.

**Comment by martinsbalodis** [comment]
Duplicate of #86 The site is sending a post request and then reloading the page.
