### ISSUE TITLE
Parent Element not found

### ISSUE THREAD

**Issue by JGAE** [martinsbalodis/web-scraper-chrome-extension#234]
Hi everybody,
I need an explanation how to use the element click selector.
I get the message parent element not found 

I used the element click selector for these links (podcasts):
https://www.spreaker.com/podcasts/podcasts-destacados

Thanks!

**Comment by JGAE** [comment]
Nobody?

**Comment by khanh96le** [comment]
The project's author seems not to manage this project anymore.

**Comment by martinsbalodis** [comment]
This means that the you a re creating a child selector of an element selector. The element that should be found by the child selector cannot be found in the page. Make sure that the the element selector can find the elements first.
