### ISSUE TITLE
new type of button were Element click selector not working

### ISSUE THREAD

**Issue by mojpr** [martinsbalodis/web-scraper-chrome-extension#235]
the web site has only one button and with every click it show new objects which i like to scrape, but currently i am only scrap two pages using element click selector and need help to cover all 50 pages.
the web site has below HTML for the button i like to click every time and get detail "<a class="x-btn x-unselectable x-btn-toolbar x-box-item x-toolbar-item x-btn-default-toolbar-small x-icon x-btn-icon x-btn-default-toolbar-small-icon" role="button" hidefocus="on" unselectable="on" id="button-1055" data-awt="simsListing-button-nextPage" data-qtip="Next Set" style="right: auto; left: 1780px; top: 0px; margin: 0px;" tabindex="0"><span id="button-1055-btnWrap" class="x-btn-wrap" unselectable="on"><span id="button-1055-btnEl" class="x-btn-button"><span id="button-1055-btnInnerEl" class="x-btn-inner x-btn-inner-center" unselectable="on">&nbsp;</span><span role="img" id="button-1055-btnIconEl" class="x-btn-icon-el x-tbar-page-next" unselectable="on" style="">&nbsp;</span></span></span></a>"

**Comment by martinsbalodis** [comment]
Try changing click type to "load more"
