### ISSUE TITLE
Unable to scrape all the pages in ajax dynamic pagination 

### ISSUE THREAD

**Issue by aravind816** [martinsbalodis/web-scraper-chrome-extension#238]
Hi Team,

  Tried to navigate to all the pages in the below URL, where the page numbers are dynamically populated during the navigation. It is not allowing to scrape more than two pages.

[Ajax Pagination Page](http://www.kmart.com.au/category/christmas/christmas-by-category/shop-all-christmas/435016)

 ##  Below is the pagination logic.

**On page 1:**  1 2 ... 7 Next>
**On Page 2:** <Previous 1 2 3 ... 7 Next>
**On Page 3:** <Previous 1 2 3 4 ... 7 Next&gt;
**On Page 4:** <Previous 1 2 3 4 5 6 7 Next>
**On Page 5:** <Previous 1 ... 4 5 6 7 Next>
**On Page 6:** <Previous 1 ... 5 6 7 Next>
**On Page 7:** <Previous 1 ... 6 7

Note: The current page number is just a normal text.﻿

## Below is the sample scrape exported:

`{"startUrl":"http://www.kmart.com.au/category/christmas/christmas-by-category/shop-all-christmas/435016","selectors":[{"parentSelectors":["_root"],"type":"SelectorElementClick","multiple":true,"id":"item","selector":"div.row div.product","clickElementSelector":"li.hoverover","clickElementUniquenessType":"uniqueText","clickType":"clickOnce","discardInitialElements":false,"delay":""},{"parentSelectors":["item"],"type":"SelectorText","multiple":false,"id":"Product name","selector":"div.product_name a","regex":"","delay":""}],"_id":"kmart-category"}`

**Comment by martinsbalodis** [comment]
Try using element click selector to handle pagination.

**Comment by aravind816** [comment]
Hi Martin,
    Element click selector didn't worked for ajax pagination when the page
numbers are populated dynamically.
