### ISSUE TITLE
Updated Code

### ISSUE THREAD

**Issue by DanSheps** [martinsbalodis/web-scraper-chrome-extension#242]
Hello,

Would it be possible to get updated code pushed to git?

I notice you are at 0.3.7 on the extension but git is only at 0.2.0

Thanks

**Comment by martinsbalodis** [comment]
The 0.3.7 extension is based on cloud scraper which has a lot of code that is not related to the extension. The 0.3.7 extension is based on cloud scraper to keep them both in sync. At the moment I don't have the time to separate them and to keep them both separate and in sync.
