### ISSUE TITLE
add start url to each data record

### ISSUE THREAD

**Issue by martinsbalodis** [martinsbalodis/web-scraper-chrome-extension#80]
When using multiple start urls or a range url there is no way to tell from which url the data was gathered.

https://groups.google.com/forum/#!topic/web-scraper/65f6xwIwOOE

**Comment by JuanjoR** [comment]
is very interesting to know, I appreciate if you could get in a new version

**Comment by LibraSun** [comment]
I agree this would be useful, especially if Scraping would record each page's URL in a dedicated column (source_url) for export. This is a great way to "link back" to the scraped page(s), for future reference.

**Comment by javorojas** [comment]
It would be nice to have the startUrl, specially when you get null results on many start urls. On top of that a re-scrape of the null results would be logic.

**Comment by hasanalanam** [comment]
Will this be implemented?

**Comment by martinsbalodis** [comment]
This feature has been added
