### ISSUE TITLE
Results not seen in "browse" after scraping but can be seen in "data preview"

### ISSUE THREAD

**Issue by varun3089** [martinsbalodis/web-scraper-chrome-extension#93]
Hi, I am trying to scrape some text data from www.espncricinfo.com. Scraping works fine for other websites but not for this one. The result set displays just the column headers not any records.

Can this website be scrape protected?

Thanks,
Varun

**Comment by martinsbalodis** [comment]
Hi, Please repost this issue in the forum. Attach an exported sitemap.
https://groups.google.com/forum/#!forum/web-scraper
